name: LE-AR-N
collections:
  sessions:
    order:
      - python-basics.md
      - geometry.md
      - data-structures.md
      - assembly-information-model.md
      - am-information-model.md
      - xr-assembly.md
      - robotic-fabrication-assembly.md
      - robotic-fabrication-control.md